<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>FKNRTD.SelfTest</RootNamespace>
    <AssemblyName>FKNRTD.SelfTest</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\FKNRTD.Core\FKNRTD.Core.csproj" />
    <ProjectReference Include="..\..\src\FKNRTD.Cli\FKNRTD.Cli.csproj" />
  </ItemGroup>
</Project>
